services:
    vpn:
        image: 192.168.1.122:6000/wireguard-pia-poce:latest
        container_name: wireguard_pia
        restart: unless-stopped
        volumes:
            # Auth token is stored here
            - /home/povilas/appdata/docker/wireguard/pia:/pia
            # If enabled, the forwarded port is dumped to /pia-shared/port.dat for potential use in other containers
            - /home/povilas/appdata/docker/wireguard/pia-shared:/pia-shared
        cap_add:
            - NET_ADMIN
            # SYS_MODULE might not be needed with a 5.6+ kernel?
           # - SYS_MODULE
        # If the kernel module isn't available, mounting the tun device may be necessary for userspace implementations
        #devices:
        #  - /dev/net/tun:/dev/net/tun
        environment:
            # The following env vars are required:
            - LOC=lt
            - USER= # add pia user
            - PASS= # add pia pass
            # The rest are optional:
            - LOCAL_NETWORK=192.168.1.0/24
            - KEEPALIVE=25
            #- VPNDNS=8.8.8.8,8.8.4.4
            - PORT_FORWARDING=1
            - PORT_FILE=/pia-shared/port.dat
            - PORT_PERSIST=1
            - PORT_SCRIPT=/scripts/trport.sh
        sysctls:
            # wg-quick fails to set this without --privileged, so set it here instead if needed
            - net.ipv4.conf.all.src_valid_mark=1
            # May as well disable ipv6. Should be blocked anyway.
            - net.ipv6.conf.default.disable_ipv6=1
            - net.ipv6.conf.all.disable_ipv6=1
            - net.ipv6.conf.lo.disable_ipv6=1
        ports:
          - 9092:9091
        
        # The container has no recovery logic. Use a healthcheck to catch disconnects.
        healthcheck:
            test: ping -c 1 www.google.lt || exit 1
            interval: 30s
            timeout: 10s
            retries: 3


    transmission:
  
      image: lscr.io/linuxserver/transmission:latest
  
      container_name: transmission
      network_mode: service:vpn
      depends_on:
        - vpn
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Vilnius
        - TRANSMISSION_WEB_HOME=/webui
      volumes:
        - ./config:/config
        - ./config/themes/transmissionic:/webui
        - ./downloads:/downloads
        - ./watch:/watch
      restart: unless-stopped
